### ISSUE TITLE
Link thickness- Can it freely vary by value?

### ISSUE THREAD

**Issue by dbrenigjones** [IntegratedTransportPlanning/gcvt#103]
Desire for line thickness to vary more, and to not be linked to the 8 colour bins. Trying to show a greater range to the user.

While ensuring it never dissapears

**Comment by bovine3dom** [comment]
Want to tweak the range shown and increase the maximum thickness so that e.g. http://gcvt.cmcaine.co.uk/map/?linkVar=V_total_pax&matVar=&scenario=GreenMax&scenarioYear=2030&percent=false&compare=false&showctrl=true&compareWith=DoNothing&compareYear=auto&showDesc=false&showClines=false&showMatHelp=true&showLinkHelp=false&showChart=true&selectedZones=[]#9.31/50.428/30.631 shows very different flows on roads out of Kiev all with similar thicknesses and colours.

To compensate for the increased thickness it would be good to have the lines become less thick as the map was zoomed out.

**Comment by dbrenigjones** [comment]
Can the thickness still vary more. More thicker to thin. I know it may start to look a little stupid at close in zoom, but it will help.

**Comment by bovine3dom** [comment]
I've almost doubled the maximum thickness and increased the maximum bounds (so there is more difference between very big numbers) - let me know if you want it even higher :)
