### ISSUE TITLE
Links width to not vary for certain attributes

### ISSUE THREAD

**Issue by dbrenigjones** [IntegratedTransportPlanning/gcvt#112]
Please could Link width should not vary for:

- Any scenario comparison
- Speed
- Volume Capacity Ratio

**Comment by dbrenigjones** [comment]
Here is an example problem when you can't see the detail of the comparison:

http://gcvt.cmcaine.co.uk/map/?linkVar=V_total_ton&matVar=&scenario=TentRail&scenarioYear=2030&percent=true&compare=true&showctrl=true&compareWith=DoNothing&compareYear=auto&showDesc=true&showClines=true&showMatHelp=false&showLinkHelp=true&showChart=false&selectedZones=[]&desiredLTypes=[3]#4.52/48.64/32.37

**Comment by bovine3dom** [comment]
I've turned it off for percentages as I couldn't fix that issue in a reasonable amount of time (essentially, we need a geometric scale so that a 2x increase and a 2x decrease look the same).

For absolute differences I've decreased the sensitivity to outliers and I think it looks pretty good - top is old behaviour, bottom is new behaviour:

![](https://i.imgur.com/gDtieCH.jpg)

Let me know if you still want to disable it for all comparisons.

I've disabled it for speed and VCR.

Closing this issue as disabling it for all comparisons if you do still want that is a 5 minute job - just let me know once you've had a chance to play with it (the changes are live on the server) :)

Edit: please also let me know if you would like the thickness of the constant-thickness lines to be thicker. Would you also like them to have the old behaviour of staying the same size on the screen no matter the zoom level?
