### ISSUE TITLE
Links should be offset

### ISSUE THREAD

**Issue by cmcaine** [IntegratedTransportPlanning/gcvt#29]
Try this: https://github.com/bbecquet/Leaflet.PolylineOffset

**Comment by Robinlovelace** [comment]
Is this to allow representation of 2 way flows? A tricky viz problem that many have tackled, few effectively... One solution is to only show 1 way flows at a time but then you need a way of defining 'in' and 'out' flows that are mutually exclusive for any setting.

**Comment by cmcaine** [comment]
The plugin above works but has some bugs (draws circles at line overlaps) and is way too slow.

With a bit of work both of those issues could probably be overcome, but dropping this for now.

Defining in and out flows sounds non-intuitive for users, so I'm not sure we can do that either.

**Comment by markjd84** [comment]
Some of the other options (none of which are very nice) 

* fudge the geography in the links file so that opposing links are separated by (say) 200m. This won't look nice zoomed out. Also I have no idea how we'd do this, it's not a simple process.
* have some kind of 'click to see links' feature where they are drawn as at present but bidirectionality can be loaded interactively when a link is clicked. Again doesn't give the 'overview' view. However this is probably easiest fix.

**Comment by markjd84** [comment]
Functionality is done, and looks great.

@dbrenigjones notes though we want to experiment with different offset levels before finally fixing one

**Comment by cmcaine** [comment]
Offsets are in. Open a new issue for any specific requests for changes to offset behaviour.

**Comment by Robinlovelace** [comment]
Awesome work implementing some cutting-edge geo visualisation tech unavailable from default R/JS leaflet pkgs, looking great.
